[build]
  # 使用 npm install，并禁用可选依赖安装，避免 Linux 平台安装 Windows 二进制
  command = "npm install --no-optional --prefer-offline --no-audit --ignore-scripts && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  VITE_APP_ENV = "production"
