[build]
  # 简化构建命令，让 Netlify 使用默认的依赖管理
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  # 指定 Node 版本，确保与 GitHub Actions 一致
  NODE_VERSION = "20.x"
  # 移除可能引起冲突的环境变量
  # 让 Netlify 使用其默认的依赖安装策略

[context.production.environment]
  VITE_APP_ENV = "production"
