[build]
  # 使用 npm install 以避免 npm ci 对 lockfile 的严格一致性校验导致失败
  command = "npm install --prefer-offline --no-audit --ignore-scripts --no-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  VITE_APP_ENV = "production"
