[build]
  # 简化构建命令，让 Netlify 使用默认的依赖管理
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  # 指定 Node 版本，确保与 GitHub Actions 一致
  NODE_VERSION = "20.x"
  # 强制安装可选依赖，解决 Rollup 二进制问题
  NPM_CONFIG_INCLUDE_OPTIONAL = "true"

[context.production.environment]
  VITE_APP_ENV = "production"
