
[build]
  command = "rm -rf node_modules && npm cache clean --force && npm ci --prefer-offline --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"
  # 强制清除缓存
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NETLIFY_SKIP_NPM_CACHE = "true"
  # Supabase 环境变量通过 Netlify 环境变量设置
  
# SPA重定向规则 - 所有请求重定向到index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 域名重定向规则
[[redirects]]
  from = "http://ramusi.cn/*"
  to = "https://ramusi.cn/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ramusi.cn/*"
  to = "https://ramusi.cn/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ramusi.cn/*"
  to = "https://ramusi.cn/:splat"
  status = 301
  force = true
