# =================================================================
# Netlify 部署配置 - 解决 Rollup 平台兼容性问题
# =================================================================

[build]
  # 使用简单的构建命令，让Netlify自动处理依赖安装
  command = "npm run build"
  # 发布目录
  publish = "dist"

# =================================================================
# 构建环境变量配置 - 关键的平台兼容性设置
# =================================================================

[build.environment]
  # Node.js 环境
  NODE_ENV = "production"
  
  # 强制跳过平台检查，允许rollup自动选择正确的平台依赖
  NPM_CONFIG_TARGET_PLATFORM = ""
  NPM_CONFIG_TARGET_ARCH = ""
  
  # 确保可选依赖正确安装（关键配置）
  NPM_CONFIG_OPTIONAL = "true"
  NPM_CONFIG_INCLUDE_OPTIONAL = "true"
  
  # 使用legacy peer deps避免依赖冲突
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  
  # 禁用平台检查，让npm自动处理平台依赖
  NPM_CONFIG_FORCE = "false"
  
  # 禁用不必要的功能提高构建速度
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  
  # 确保使用清洁安装
  NPM_CONFIG_PREFER_OFFLINE = "false"
  
  # 构建环境标识
  VITE_APP_ENV = "production"

# =================================================================
# SPA 重定向配置
# =================================================================

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =================================================================
# 安全头配置
# =================================================================

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# 静态资源缓存优化
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
