[build]
  # 使用 npm 安装，包含可选依赖以确保平台特定二进制文件被正确安装
  command = "npm install --prefer-offline --no-audit --ignore-scripts --include=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_INCLUDE_OPTIONAL = "true"

[context.production.environment]
  VITE_APP_ENV = "production"
