[build]
  # 使用 npm install，并允许可选依赖安装（需要安装 Rollup 的平台二进制）
  command = "npm install --prefer-offline --no-audit --ignore-scripts && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  VITE_APP_ENV = "production"
