[build]
  # 使用 npm 安装，允许安装平台匹配的可选依赖（如 @rollup/rollup-linux-x64-gnu）
  command = "npm install --prefer-offline --no-audit --ignore-scripts && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_INCLUDE_OPTIONAL = "true"

[context.production.environment]
  VITE_APP_ENV = "production"
