[build]
  # 优化构建命令，使用 --legacy-peer-deps 解决依赖冲突
  command = "npm install --legacy-peer-deps --prefer-offline --no-audit --include=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_INCLUDE_OPTIONAL = "true"

[context.production.environment]
  VITE_APP_ENV = "production"
