name: Build and Verification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'
        timeout-minutes: 2

      - name: Install dependencies (npm ci)
        run: |
          echo "📦 安装依赖 (npm ci)..."
          npm ci
        timeout-minutes: 5

      - name: Type check
        run: npm run type-check
        timeout-minutes: 3

      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Build
        run: npm run build
        timeout-minutes: 5

      - name: Deploy
        run: npm run deploy
        timeout-minutes: 5

  verification:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'
        timeout-minutes: 2

      - name: Install dependencies (npm ci)
        run: |
          echo "📦 安装依赖 (npm ci)..."
          npm ci
        timeout-minutes: 5

      - name: Type check
        run: npm run type-check
        timeout-minutes: 3

      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Health Check - Accessibility
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: |
          echo "⏱️ 站点可访问性检查开始: $(date)"
          URL="https://ramusi.cn"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$code" = "200" ]; then
            echo "✅ 可访问 (HTTP $code)"
          else
            echo "❌ 访问失败 (HTTP $code)"
            exit 1
          fi
          echo "⏱️ 完成: $(date)"

      - name: Health Check - Basic Content
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: |
          echo "⏱️ 内容检查开始: $(date)"
          content=$(curl -s https://ramusi.cn)
          if echo "$content" | grep -qi "Ramusi"; then
            echo "✅ 关键内容存在"
          else
            echo "❌ 未找到关键内容: Ramusi"
            exit 1
          fi
          echo "⏱️ 完成: $(date)"

      - name: Health Check Summary
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: |
          echo "📊 健康检查完成 (可访问性 + 内容)"