version: '3.8'

services:
  web:
    build: .
    container_name: advanced-tools-navigation
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge
